class_name Faces
extends RefCounted
## Kaomoji faces a player can pick. Ids are what the server stores; each maps to
## a texture in res://assets/faces (generated by branding/make_faces.py).

const LIST := [
	[":D", "grin"], [":)", "smile"], [":3", "cat"], [":P", "tongue"], [";)", "wink"], [":O", "wow"],
	["xD", "xd"], ["B)", "cool"], ["^_^", "happy"], ["owo", "owo"], ["uwu", "uwu"], [">_<", "squint"],
	["T_T", "cry"], ["-_-", "meh"], [":|", "flat"], ["<3", "love"],
]
## Shown on a ragdoll, not selectable.
const SAD := ":("

static var _cache := {}


static func slug(id: String) -> String:
	if id == SAD:
		return "sad"
	for f in LIST:
		if f[0] == id:
			return f[1]
	return "grin"


static func texture(id: String) -> Texture2D:
	var s := slug(id)
	if not _cache.has(s):
		_cache[s] = load("res://assets/faces/%s.png" % s)
	return _cache[s]
