class_name Strings
extends RefCounted
## UI text: key -> [English, Russian]. Plural keys hold forms joined by "|":
## English "one|many", Russian "one|few|many".

const TABLE := {
	# General
	"yes": ["Yes", "Да"],
	"cancel": ["Cancel", "Отмена"],
	"close": ["Close", "Закрыть"],
	"load_failed": ["Couldn't load. Check your internet", "Не получилось загрузить. Проверь интернет"],
	"loading_places": ["Loading places...", "Загружаем плейсы..."],
	"retry": ["Try again", "Попробовать снова"],
	"connecting": ["Connecting...", "Подключаемся..."],
	"one_sec": ["One sec...", "Секунду..."],
	"done": ["Done", "Готово"],
	"apply": ["Apply", "Применить"],
	"save": ["Save", "Сохранить"],
	"saved": ["Saved", "Сохранено"],
	"saving": ["Saving...", "Сохраняем..."],
	"time_now": ["just now", "только что"],
	"time_min": ["{0} min ago", "{0} мин назад"],
	"time_hour": ["{0} h ago", "{0} ч назад"],
	"time_day": ["{0} d ago", "{0} дн назад"],
	"session_expired": ["Session expired, please sign in again", "Сессия истекла, войди заново"],
	"err_request": ["Couldn't send the request", "Не получилось отправить запрос"],
	"err_network": ["No connection to the server. Check your internet", "Нет связи с сервером. Проверь интернет"],
	"err_server": ["Server error ({0})", "Ошибка сервера ({0})"],
	"err_ws_connect": ["Couldn't connect to the game server", "Не удалось подключиться к игровому серверу"],
	"err_ws_lost": ["Connection to the server was lost", "Соединение с сервером потеряно"],
	"err_ws_unavailable": ["Game server is unavailable", "Игровой сервер недоступен"],
	"err_duplicate": ["You joined from another device", "Ты зашёл(ла) в игру с другого устройства"],

	# Auth
	"tagline": ["Play, dress up and hang out with friends", "Играй, наряжайся и тусуйся с друзьями"],
	"sign_in": ["Sign in", "Вход"],
	"sign_up": ["Sign up", "Регистрация"],
	"username": ["Username", "Логин"],
	"display_name_hint": ["Display name (what others see)", "Как тебя называть (ник)"],
	"password": ["Password", "Пароль"],
	"password_repeat": ["Repeat password", "Повтори пароль"],
	"create_account": ["Create account", "Создать аккаунт"],
	"register_hint": ["Username: latin letters, digits and _. Password: 6+ characters.", "Логин: латиница, цифры и _. Пароль от 6 символов."],
	"login_hint": ["No account yet? Tap Sign up, it takes a minute.", "Нет аккаунта? Жми «Регистрация», это быстро."],
	"bad_username": ["Username: 3–20 characters, latin letters, digits and _", "Логин: 3–20 символов, латиница, цифры и _"],
	"bad_password": ["Password must be at least 6 characters", "Пароль должен быть от 6 символов"],
	"passwords_mismatch": ["Passwords don't match", "Пароли не совпадают"],
	"welcome_name": ["Welcome, {0}!", "Добро пожаловать, {0}!"],

	# Navigation
	"nav_home": ["Home", "Главная"],
	"nav_friends": ["Friends", "Друзья"],
	"nav_avatar": ["Avatar", "Аватар"],
	"nav_shop": ["Shop", "Магазин"],
	"nav_settings": ["Settings", "Настройки"],

	# Home
	"hello_name": ["Hi, {0}!", "Привет, {0}!"],
	"home_sub": ["What are we playing today?", "Во что сегодня играем?"],
	"friends_online": ["Friends online", "Друзья онлайн"],
	"servers_title": ["Servers", "Серверы"],
	"new_server": ["New server", "Новый сервер"],
	"loading_servers": ["Loading servers...", "Загружаем серверы..."],
	"featured_tag": ["FEATURED", "ИЗБРАННОЕ"],
	"playground": ["Playground", "Детская площадка"],
	"playground_desc": ["Slides, swings, trampolines, a hedge maze, a pond and parkour above the clouds. Up to 10 players per server.", "Горки, качели, батуты, лабиринт, пруд и паркур над облаками. До 10 игроков на сервер."],
	"play": ["Play", "Играть"],
	"playing_now": ["{0} {1} on the playground now", "{0} {1} сейчас на площадке"],
	"players_word": ["player|players", "игрок|игрока|игроков"],
	"friends_word": ["friend|friends", "друг|друга|друзей"],
	"no_servers": ["No servers yet. Tap Play and the first one is yours.", "Пока ни одного сервера. Жми «Играть», и первый будет твоим."],
	"friends_here": ["Friends here: {0}", "Здесь друзья: {0}"],
	"server_id": ["Server #{0}", "Сервер #{0}"],
	"full": ["Full", "Полный"],
	"join": ["Join", "Войти"],
	"on_playground": ["On the playground", "На площадке"],
	"in_menu": ["In menu", "В меню"],

	# Friends
	"friends_sub": ["Find friends by name and play on the same server", "Найди друзей по нику и играйте на одном сервере"],
	"search_players": ["Search players by name or username", "Поиск игроков по нику или логину"],
	"my_friends": ["My friends", "Мои друзья"],
	"requests": ["Requests", "Заявки"],
	"sent": ["Sent", "Отправленные"],
	"no_friends": ["No friends yet. Find someone with the search above!", "Пока друзей нет. Найди кого-нибудь через поиск сверху!"],
	"no_requests": ["No new requests", "Новых заявок нет"],
	"no_sent": ["You haven't sent any requests", "Ты никому не отправлял(а) заявок"],
	"nobody_found": ["Nobody found for “{0}”", "Никого не нашли по запросу «{0}»"],
	"playing_on": ["Playing: {0}", "Играет: {0}"],
	"online": ["Online", "В сети"],
	"offline": ["Offline", "Не в сети"],
	"join_friend": ["Join", "Присоединиться"],
	"remove": ["Remove", "Удалить"],
	"accept": ["Accept", "Принять"],
	"decline": ["Decline", "Отклонить"],
	"cancel_request": ["Cancel request", "Отменить"],
	"add": ["Add", "Добавить"],
	"add_friend": ["Add friend", "Добавить в друзья"],
	"remove_friend": ["Remove friend", "Удалить из друзей"],
	"accept_request": ["Accept request", "Принять заявку"],
	"now_friends_with": ["You and {0} are friends now", "Теперь вы друзья с {0}"],
	"now_friends": ["You're friends now!", "Вы теперь друзья!"],
	"request_sent": ["Friend request sent", "Заявка отправлена"],
	"request_sent_short": ["Sent", "Отправлено"],
	"friends_badge": ["Friends", "Друзья"],
	"request_cancelled": ["Request cancelled", "Заявка отменена"],
	"remove_friend_q": ["Remove friend?", "Удалить из друзей?"],
	"remove_friend_body": ["{0} will disappear from your friends list.", "{0} пропадёт из списка друзей."],
	"removed": ["Removed", "Удалено"],
	"mutual_request": ["They had already asked you, so you're friends now!", "У вас была встречная заявка, теперь вы друзья!"],
	"block": ["Block", "Заблокировать"],
	"unblock": ["Unblock", "Разблокировать"],
	"block_q": ["Block {0}?", "Заблокировать {0}?"],
	"block_body": ["You won't see their chat messages and they can't send you friend requests.", "Ты не увидишь их сообщения в чате, и они не смогут кинуть тебе заявку в друзья."],
	"blocked_done": ["Player blocked", "Игрок заблокирован"],
	"unblocked": ["Player unblocked", "Игрок разблокирован"],

	# Profile
	"loading_profile": ["Loading profile...", "Загружаем профиль..."],
	"no_bio": ["Hasn't written anything about themselves yet", "Пока ничего о себе не рассказал(а)"],
	"member_since": ["member since", "с нами с"],

	# Avatar
	"wave": ["Wave", "Помахать"],
	"random": ["Random", "Случайно"],
	"like_melly": ["Classic Melly", "Как у Melly"],
	"colors": ["Colors", "Цвета"],
	"hats": ["Hats", "Шапки"],
	"profile": ["Profile", "Профиль"],
	"what_to_paint": ["What to paint", "Что красим"],
	"whole_body": ["Whole body", "Всё тело"],
	"both_arms": ["Both arms", "Обе руки"],
	"both_legs": ["Both legs", "Обе ноги"],
	"part_head": ["Head", "Голова"],
	"part_torso": ["Torso", "Торс"],
	"part_arm_l": ["Left arm", "Левая рука"],
	"part_arm_r": ["Right arm", "Правая рука"],
	"part_leg_l": ["Left leg", "Левая нога"],
	"part_leg_r": ["Right leg", "Правая нога"],
	"color": ["Color", "Цвет"],
	"custom_color": ["Custom color", "Свой цвет"],
	"hat_none": ["No hat", "Без шапки"],
	"hat_catears": ["Cat ears", "Кошачьи ушки"],
	"hat_cap": ["Cap", "Кепка"],
	"hat_crown": ["Crown", "Корона"],
	"hat_halo": ["Halo", "Нимб"],
	"hat_tophat": ["Top hat", "Цилиндр"],
	"hat_flower": ["Flower", "Цветочек"],
	"hat_headphones": ["Headphones", "Наушники"],
	"nick_label": ["Display name (everyone on the server sees it)", "Ник (видят все на сервере)"],
	"nick": ["Display name", "Ник"],
	"about_me": ["About me", "О себе"],
	"bio_hint": ["A few words about you (up to 160 characters)", "Пара слов о себе (до 160 символов)"],
	"login_is": ["Username: @{0}", "Логин: @{0}"],
	"nick_short": ["Display name is too short", "Ник слишком короткий"],
	"look_saved": ["Look saved", "Образ сохранён"],

	# Settings
	"game": ["Game", "Игра"],
	"camera_sensitivity": ["Camera sensitivity", "Чувствительность камеры"],
	"volume": ["Volume", "Громкость"],
	"graphics": ["Graphics", "Графика"],
	"quality_low": ["Fast", "Быстрая"],
	"quality_medium": ["Balanced", "Средняя"],
	"quality_high": ["Pretty", "Красивая"],
	"graphics_note": ["Fast turns off shadows and effects; use it on older phones.", "«Быстрая» выключает тени и эффекты, выбирай её на старых телефонах."],
	"show_fps": ["Show FPS and ping", "Показывать FPS и пинг"],
	"language": ["Language", "Язык"],
	"about": ["About", "О приложении"],
	"server_is": ["Server: {0}", "Сервер: {0}"],
	"checking_server": ["Checking connection...", "Проверяем связь..."],
	"server_ok": ["Server is fine, {0} ms, accounts: {1}", "Сервер в порядке, отклик {0} мс, аккаунтов: {1}"],
	"server_down": ["Server unavailable: {0}", "Сервер недоступен: {0}"],
	"account": ["Account", "Аккаунт"],
	"signed_in_as": ["Signed in as @{0}", "Вошли как @{0}"],
	"change_password": ["Change password", "Сменить пароль"],
	"current_password": ["Current password", "Текущий пароль"],
	"new_password": ["New password (6+ characters)", "Новый пароль (от 6 символов)"],
	"password_changed": ["Password changed. Other devices were signed out", "Пароль изменён. Другие устройства разлогинены"],
	"log_out": ["Sign out", "Выйти из аккаунта"],
	"log_out_q": ["Sign out?", "Выйти?"],
	"log_out_body": ["You'll need your username and password to come back.", "Чтобы вернуться, понадобятся логин и пароль."],
	"blocked_players": ["Blocked players", "Заблокированные"],
	"nobody_blocked": ["You haven't blocked anyone", "Ты никого не блокировал(а)"],

	# Game
	"joining_playground": ["Joining the playground...", "Подключаемся к площадке..."],
	"reconnecting": ["Reconnecting ({0}/3)...", "Переподключаемся ({0}/3)..."],
	"to_menu": ["Main menu", "В меню"],
	"other_server": ["Another server", "Другой сервер"],
	"finding_server": ["Looking for a free server...", "Ищем свободный сервер..."],
	"welcome_server": ["You're on “{0}”. Have fun!", "Ты на сервере «{0}». Веселись!"],
	"sys_joined": ["{0} joined the playground", "{0} зашёл(ла) на площадку"],
	"sys_left": ["{0} left", "{0} ушёл(ла)"],
	"sys_muted": ["You were muted on this server", "Тебя замутили на этом сервере"],
	"sys_unmuted": ["You can chat again", "Ты снова можешь писать в чат"],
	"adm_title": ["Admin", "Админка"],
	"adm_fly": ["Fly", "Полёт"],
	"adm_fly_hint": ["Flying: move where you look, Space / E / jump up, Q down, Shift faster.", "Полёт: летишь куда смотришь, пробел / E / прыжок вверх, Q вниз, Shift быстрее."],
	"adm_speed": ["Speed {0}", "Скорость {0}"],
	"adm_speed_normal": ["Normal speed", "Обычная скорость"],
	"adm_players": ["Players on this server", "Игроки на сервере"],
	"adm_alone": ["Nobody else here yet", "Больше никого нет"],
	"adm_mute": ["Mute", "Мут"],
	"adm_unmute": ["Unmute", "Размут"],
	"adm_tp": ["To", "К нему"],
	"adm_bring": ["Bring", "Ко мне"],
	"adm_kill": ["Kill", "Убить"],
	"adm_kick": ["Kick", "Кик"],
	"adm_announce": ["Announcement for this server", "Объявление для сервера"],
	"adm_send": ["Send", "Отправить"],
	"adm_done_mute": ["{0} is muted here", "{0} замучен на этом сервере"],
	"adm_done_unmute": ["{0} can chat again", "{0} снова может писать"],
	"adm_done_kick": ["{0} was kicked", "{0} кикнут"],
	"adm_done_bring": ["Brought {0}", "{0} перенесён к тебе"],
	"adm_done_kill": ["{0} is out", "{0} отправлен на респавн"],
	"sys_slow": ["Slow down, the chat can't keep up :)", "Помедленнее, чат не успевает :)"],
	"chat_placeholder": ["Say something...", "Написать в чат..."],
	"stats": ["{0} FPS · ping {1}", "{0} FPS · пинг {1}"],
	"you_fell_apart": ["Oof! Respawning...", "Ой! Собираемся обратно..."],
	"island_reached": ["You made it to the clouds!", "Ты добрался(ась) до облаков!"],
	"maze_solved": ["Maze solved! You found the golden flower", "Лабиринт пройден! Золотой цветок твой"],
	"leave_q": ["Leave the playground?", "Выйти с площадки?"],
	"leave_body": ["You'll go back to the main menu.", "Вернёшься в главное меню."],
	"leave_game": ["Leave game", "Выйти из игры"],
	"reset_character": ["Reset character", "Ресетнуться"],
	"resume": ["Resume", "Продолжить"],
	"players": ["Players", "Игроки"],
	"controls": ["Controls", "Управление"],
	"players_on_server": ["Players on server ({0}/{1})", "Игроки на сервере ({0}/{1})"],
	"its_you": ["that's you", "это ты"],
	"help_move": ["Move: left thumb (joystick) or WASD. Shift to sprint on PC.", "Ходить: левый палец (джойстик) или WASD. Shift на ПК для бега."],
	"help_camera": ["Camera: drag with the right thumb, or hold the right mouse button.", "Камера: веди правым пальцем или держи правую кнопку мыши."],
	"help_zoom": ["Zoom: pinch or mouse wheel. Zoom all the way in (or the camera button) for first person.", "Зум: щипок или колесо мыши. Приблизь до упора (или кнопка камеры) для вида от первого лица."],
	"help_jump": ["Jump: big button on the right or Space. Big falls hurt!", "Прыжок: большая кнопка справа или пробел. Падать с высоты больно!"],
	"help_emotes": ["Emotes: the smiley button or B opens the emote wheel.", "Эмоции: кнопка со смайликом или B открывает колесо эмоций."],
	"help_chat": ["Chat: the chat button or Enter.", "Чат: кнопка чата или Enter."],
	"help_reset": ["Stuck? Menu → Reset character (or R).", "Застрял(а)? Меню → Ресетнуться (или R)."],
	"emote_wave": ["Wave", "Привет"],
	"emote_heart": ["Hearts", "Сердечки"],
	"emote_dance": ["Dance", "Танец"],
	"emote_cheer": ["Cheer", "Ура!"],
	"emote_sit": ["Sit", "Сесть"],
	"emote_clap": ["Clap", "Хлопать"],
	"emote_laugh": ["Laugh", "Смех"],

	"places": ["Places", "Плейсы"],
	"by": ["by", "от"],
	"n_playing": ["{0} playing", "играют: {0}"],
	"n_visits": ["{0} visits", "посещений: {0}"],
	"rating": ["{0} liked", "{0} лайков"],
	"back": ["Back", "Назад"],
	"loading": ["Loading...", "Загрузка..."],
	"about_place": ["About", "Описание"],
	"created_on": ["Created {0}", "Создан {0}"],
	"play_hint": ["Play puts you on a server with your friends if any are playing.", "«Играть» закинет тебя на сервер к друзьям, если они играют."],
	"update_title": ["Time to update", "Пора обновиться"],
	"update_body": ["A new version of Meltiew is out. Download it to keep playing.", "Вышла новая версия Meltiew. Скачай её, чтобы играть дальше."],
	"update_button": ["Download update", "Скачать обновление"],
	"update_later": ["Later", "Позже"],
	"your_version": ["Your version: {0}", "Твоя версия: {0}"],
	"kicked_banned": ["Your account was banned", "Твой аккаунт заблокирован"],
	"kicked_admin": ["An admin removed you from the server", "Админ выгнал тебя с сервера"],
	"server_closed": ["This server was closed", "Этот сервер закрыли"],
	"role_owner": ["OWNER", "ОВНЕР"],
	"role_admin": ["ADMIN", "АДМИН"],

	# Round 4
	"messages": ["Messages", "Сообщения"],
	"chats": ["Chats", "Чаты"],
	"dm_requests": ["Requests", "Заявки"],
	"no_chats": ["No conversations yet. Open a profile and press Message.", "Пока нет диалогов. Открой профиль и нажми «Написать»."],
	"no_requests_dm": ["No message requests", "Заявок на диалог нет"],
	"pick_chat": ["Pick a conversation", "Выбери диалог"],
	"you_prefix": ["You: ", "Ты: "],
	"type_message": ["Message...", "Сообщение..."],
	"message": ["Message", "Написать"],
	"dm_waiting": ["Message request sent. You can write more once {0} accepts it.", "Заявка отправлена. Написать ещё можно будет, когда {0} её примет."],
	"dm_request_from": ["{0} wants to chat with you", "{0} хочет с тобой пообщаться"],
	"dm_first_message": ["You're not friends yet: your first message goes as a request.", "Вы ещё не друзья: первое сообщение уйдёт как заявка на диалог."],
	"dm_unavailable_note": ["Messages aren't available for this conversation.", "В этом диалоге сообщения недоступны."],
	"friends_online_n": ["{0} online of {1}", "{0} в сети из {1}"],
	"search_everything": ["Search players and places", "Поиск игроков и плейсов"],
	"search_places": ["Search places", "Поиск плейсов"],
	"no_places_found": ["No places found", "Ничего не нашлось"],
	"friends_hidden": ["Friends list is hidden", "Список друзей скрыт"],
	"report": ["Report", "Пожаловаться"],
	"report_title": ["Report {0}", "Жалоба на {0}"],
	"report_chat": ["Chat", "Чат"],
	"report_name": ["Name", "Ник"],
	"report_avatar": ["Avatar", "Аватар"],
	"report_cheating": ["Cheating", "Читы"],
	"report_other": ["Other", "Другое"],
	"report_details": ["What happened? (optional)", "Что случилось? (необязательно)"],
	"report_send": ["Send report", "Отправить"],
	"faces": ["Face", "Лицо"],
	"interface": ["Interface", "Интерфейс"],
	"ui_size": ["Interface size", "Размер интерфейса"],
	"ui_size_auto": ["Automatic size", "Размер автоматически"],
	"lang_fallback_note": ["The app isn't translated to this language yet, so it shows English. Places that have their own translations will use it.", "Приложение пока не переведено на этот язык, поэтому показывает английский. Плейсы со своими переводами будут на нём."],
	"console": ["Console", "Консоль"],
	"place_unsupported": ["Scripts can't run on this device, so the place may not work.", "На этом устройстве скрипты не запускаются, поэтому плейс может не работать."],
	"loading_place": ["Loading the place...", "Загружаем плейс..."],
	"inventory": ["Inventory", "Инвентарь"],
	"eco_pieces": ["Pieces", "Кусочки"],
	"eco_orbs": ["Orbs", "Опыт"],
	"eco_pieces_about": ["Pieces are bought and spent on accessories, faces and gamepasses.", "Кусочки покупаются и тратятся на аксессуары, лица и геймпассы."],
	"eco_pay_soon": ["Buying pieces opens very soon!", "Покупка кусочков откроется совсем скоро!"],
	"eco_buy_for": ["Buy for {0} ₽", "Купить за {0} ₽"],
	"eco_pay_opened": ["The payment page opened in your browser", "Страница оплаты открылась в браузере"],
	"eco_pay_note": ["Payment through SBP or crypto (RollyPay). By paying you accept the terms and the privacy policy.", "Оплата через СБП или криптовалютой (RollyPay). Оплачивая, ты принимаешь пользовательское соглашение и политику конфиденциальности."],
	"eco_terms": ["Terms", "Соглашение"],
	"eco_privacy": ["Privacy", "Конфиденциальность"],
	"eco_support": ["Support", "Поддержка"],
	"eco_paid": ["Payment received: +{0} pieces!", "Оплата прошла: +{0} кусочков!"],
	"eco_quests": ["Daily quests", "Задания на сегодня"],
	"eco_daily_note": ["Every day you come in: +{0} orbs. Three new quests each day.", "Каждый день за заход: +{0} опыта. Каждый день три новых задания."],
	"eco_claim": ["Claim +{0}", "Забрать +{0}"],
	"eco_claimed": ["Claimed", "Получено"],
	"eco_go": ["Go · +{0}", "Перейти · +{0}"],
	"eco_daily_bonus": ["+{0} orbs for coming today!", "+{0} опыта за сегодняшний заход!"],
	"eco_you_have": ["You have", "У тебя"],
	"eco_buy_pass": ["Buy for {0} pieces", "Купить за {0} кусочков"],
	"eco_passes": ["Gamepasses", "Геймпассы"],
	"eco_owned": ["Yours", "Есть"],
	"buy": ["Buy", "Купить"],
	"shop_reset_look": ["What I wear", "Как сейчас"],
	"shop_wear_all": ["Wear this look", "Надеть образ"],
	"shop_wear": ["Wear", "Надеть"],
	"shop_worn": ["On you", "Надето"],
	"shop_buy_first": ["Buy what you're trying on first", "Сначала купи то, что примеряешь"],
	"shop_buy_q": ["Buy {0}?", "Купить «{0}»?"],
	"shop_buy_text": ["{0} for {1}. It stays yours forever.", "«{0}» за {1}. Останется у тебя навсегда."],
	"shop_bought": ["{0} is yours!", "«{0}» теперь твоё!"],
	"shop_more": ["More in the shop", "Ещё в магазине"],
	"eco_buy_items_q": ["Buy what you're trying on?", "Купить то, что примеряешь?"],
	"eco_buy_items_text": ["Some of this isn't yours yet. Buy it and save the look?", "Часть вещей пока не твоя. Купить их и сохранить образ?"],
	"eco_buy_save": ["Buy and save", "Купить и сохранить"],
	"eco_shop_hint": ["Tap to try on. Items with a price are bought when you save.", "Нажми, чтобы примерить. Вещи с ценой покупаются при сохранении."],
	"eco_pass_new": ["New gamepass", "Новый геймпасс"],
	"eco_pass_name": ["Name", "Название"],
	"eco_pass_price": ["Price in pieces", "Цена в кусочках"],
	"eco_pass_desc": ["What it gives", "Что даёт"],
	"eco_pass_pick_image": ["Picture...", "Картинка..."],
	"eco_pass_hint": ["Players buy passes for pieces; you get 95%. Scripts: MarketplaceService:UserOwnsGamePassAsync(player.UserId, id).", "Игроки покупают пассы за кусочки, тебе достаётся 95%. В скриптах: MarketplaceService:UserOwnsGamePassAsync(player.UserId, id)."],
	"eco_pass_sold": ["#{0} · {1} sold", "#{0} · продано {1}"],
	"q_playground10": ["Play on the Playground for 10 minutes", "Поиграй на площадке 10 минут"],
	"q_friend": ["Play in any place together with a friend", "Поиграй в любом плейсе вместе с другом"],
	"q_places3": ["Visit 3 different places", "Зайди в 3 разных плейса"],
	"q_play30": ["Play for 30 minutes", "Поиграй 30 минут"],
	"q_like": ["Like a place", "Лайкни плейс"],
	"q_emotes5": ["Use 5 emotes in the game", "Используй 5 эмоций в игре"],
	"inventory_empty": ["Nothing here yet", "Пока пусто"],
	"telegram": ["Our Telegram channel", "Наш Telegram-канал"],
	"privacy": ["Privacy", "Приватность"],
	"hide_friends": ["Hide my friends list", "Скрыть список друзей"],
	"bd_title": ["Your date of birth", "Твоя дата рождения"],
	"bd_why": ["We need it to set up chat safely. Enter the real one: after one free fix it can only be changed once every 6 months.", "Она нужна, чтобы безопасно настроить чат. Укажи настоящую: после одного бесплатного исправления менять её можно раз в полгода."],
	"bd_change_why": ["Pick your real date of birth. After this change the next one is possible in 6 months.", "Выбери настоящую дату рождения. После этой смены следующая будет доступна через полгода."],
	"bd_change_free": ["Fix date of birth (one free change)", "Исправить дату рождения (одна бесплатная смена)"],
	"bd_change": ["Change date of birth", "Сменить дату рождения"],
	"bd_next_change": ["You can change it again on {0}.", "Снова сменить можно будет {0}."],
	"bd_label": ["Date of birth", "Дата рождения"],
	"bd_day": ["Day", "День"],
	"bd_month": ["Month", "Месяц"],
	"bd_year": ["Year", "Год"],
	"bd_months": ["January,February,March,April,May,June,July,August,September,October,November,December", "января,февраля,марта,апреля,мая,июня,июля,августа,сентября,октября,ноября,декабря"],
	"bd_later": ["Later", "Позже"],
	"bd_incomplete": ["Pick day, month and year", "Выбери день, месяц и год"],
	"bd_is": ["Date of birth: {0}", "Дата рождения: {0}"],
	"birthdate_needed": ["Enter your date of birth to play", "Укажи дату рождения, чтобы играть"],
	"rules_kid": ["Under 13: chat and direct messages are off.", "До 13 лет: чат и личные сообщения выключены."],
	"rules_teen": ["Under 16: chat and direct messages are filtered.", "До 16 лет: в чате и личных сообщениях работает фильтр."],
	"rules_older_teen": ["Under 18: game chat is filtered.", "До 18 лет: в игровом чате работает фильтр."],
	"rules_adult": ["18+: no filters.", "18+: без фильтров."],
	"sys_no_chat": ["Chat is off for your age", "Чат недоступен по возрасту"],

	# World signs
	"sign_trampolines": ["trampolines", "батуты"],
	"sign_maze": ["hedge maze", "лабиринт"],
	"sign_parkour": ["parkour to the clouds", "паркур до облаков"],
	"sign_pond": ["duck pond", "утиный пруд"],
	"sign_icecream": ["ICE CREAM", "МОРОЖЕНОЕ"],

	# Studio
	"nav_studio": ["Studio", "Студия"],
	"studio_sub": ["Build your own places, script them in Luau and publish", "Строй свои плейсы, пиши скрипты на Luau и публикуй"],
	"bad_image": ["That image didn't work. Try a PNG or JPG up to 2 MB", "Картинка не подошла. Нужен PNG или JPG до 2 МБ"],
	"st_explorer": ["Explorer", "Проводник"],
	"se_paste": ["Paste", "Вставить"],
	"st_acc_count": ["Accessories: {0}", "Аксессуаров: {0}"],
	"anim_pick": ["Animation", "Анимация"],
	"an_title": ["Animator", "Аниматор"],
	"an_name": ["Animation name", "Название анимации"],
	"an_length": ["Length, s", "Длина, с"],
	"an_loop": ["Loop", "По кругу"],
	"nav_communities": ["Communities", "Сообщества"],
	"cm_sub": ["Teams, clubs and studios: chat, roles and places made together", "Команды, клубы и студии: чаты, роли и совместные плейсы"],
	"cm_create": ["Create", "Создать"],
	"cm_create_for": ["Create for", "Создать за"],
	"cm_price_hint": ["A community costs 10 pieces or 100 orbs. You'll be its owner.", "Сообщество стоит 10 кусочков или 100 опыта. Ты станешь его владельцем."],
	"cm_created": ["Community created!", "Сообщество создано!"],
	"cm_search": ["Search communities", "Поиск сообществ"],
	"cm_mine": ["Yours", "Твои"],
	"cm_popular": ["Popular", "Популярные"],
	"cm_found": ["Found", "Найдено"],
	"cm_none": ["Nothing here yet. Make the first one!", "Пока пусто. Создай первое!"],
	"cm_members": ["{0} members", "Участников: {0}"],
	"cm_by": ["by {0}", "создатель {0}"],
	"cm_name": ["Name", "Название"],
	"cm_desc": ["What is it about?", "О чём оно?"],
	"cm_join": ["Join", "Вступить"],
	"cm_leave": ["Leave", "Выйти"],
	"cm_leave_q": ["Leave the community?", "Выйти из сообщества?"],
	"cm_banned": ["You're banned here", "Ты тут забанен"],
	"cm_channels": ["Channels", "Каналы"],
	"cm_people": ["Members", "Участники"],
	"cm_places": ["Places", "Плейсы"],
	"cm_settings": ["Settings", "Настройки"],
	"cm_write": ["Message #{0}", "Написать в #{0}"],
	"cm_join_to_write": ["Join to write here", "Вступи, чтобы писать"],
	"cm_cant_write": ["Your role can't write in this channel", "Твоей роли нельзя писать в этот канал"],
	"cm_no_messages": ["No messages yet. Say hi!", "Сообщений пока нет. Поздоровайся!"],
	"cm_role": ["Role", "Роль"],
	"my_profile": ["My profile", "Мой профиль"],
	"pf_communities": ["Communities: {0}", "Сообщества: {0}"],
	"pf_places": ["Places: {0}", "Плейсы: {0}"],
	"st_of_community": ["Community: {0}", "Сообщество: {0}"],
	"st_saved_by": ["saved by {0}", "сохранил {0}"],
	"st_owner": ["Whose place", "Чей плейс"],
	"st_owner_me": ["Mine", "Мой"],
	"st_give_community": ["Give to a community", "Передать сообществу"],
	"st_give": ["Give", "Передать"],
	"st_give_q": ["Give {0} to {1}?", "Передать {0} сообществу {1}?"],
	"st_give_text": ["Its builders will edit and publish it with you. Only the community's owner can give it back.", "Его строители смогут редактировать и публиковать его вместе с тобой. Вернуть его может только владелец сообщества."],
	"st_conflict_status": ["Not saved: someone saved a newer version", "Не сохранено: кто-то сохранил версию новее"],
	"st_conflict_text": ["Your version will replace theirs. Cancel keeps your changes here unsaved, so you can talk it over first.", "Твоя версия заменит их. «Отмена» оставит твои правки несохранёнными, чтобы сначала договориться."],
	"st_save_over": ["Save over", "Сохранить поверх"],
	"cm_role_owner": ["Owner", "Владелец"],
	"cm_role_admin": ["Admin", "Админ"],
	"cm_role_builder": ["Builder", "Строитель"],
	"cm_role_member": ["Member", "Участник"],
	"cm_remove": ["Remove", "Убрать"],
	"cm_remove_q": ["Remove {0} from the community?", "Убрать {0} из сообщества?"],
	"cm_ban": ["Ban", "Бан"],
	"cm_ban_q": ["Ban {0}?", "Забанить {0}?"],
	"cm_ban_text": ["They leave and can't come back.", "Игрок выйдет и не сможет вернуться."],
	"cm_new_place": ["New place for the community", "Новый плейс сообщества"],
	"cm_no_places": ["No places yet", "Плейсов пока нет"],
	"cm_roles": ["Roles", "Роли"],
	"cm_roles_hint": ["Higher rank = more say. You edit roles below yours. Tap a permission to turn it on or off.", "Чем выше ранг, тем больше прав. Менять можно роли ниже твоей. Нажми на право, чтобы включить или выключить."],
	"cm_role_name": ["New role", "Новая роль"],
	"cm_rank": ["rank ", "ранг "],
	"cm_add": ["Add", "Добавить"],
	"cm_post_rank": ["write from rank ", "писать с ранга "],
	"cm_channel_name": ["New channel", "Новый канал"],
	"cm_delete_channel_q": ["Delete #{0}?", "Удалить #{0}?"],
	"cm_delete_role_q": ["Delete the role {0}?", "Удалить роль {0}?"],
	"cm_delete_role_text": ["Its members get the lowest role.", "Её участники получат самую младшую роль."],
	"cm_delete": ["Delete community", "Удалить сообщество"],
	"cm_delete_q": ["Delete {0}?", "Удалить {0}?"],
	"cm_delete_text": ["Channels and roles go away; places go back to whoever made them.", "Каналы и роли пропадут, плейсы вернутся их создателям."],
	"cm_perm_manage": ["Manage", "Управление"],
	"cm_perm_moderate": ["Moderate", "Модерация"],
	"cm_perm_places": ["Build places", "Строить плейсы"],
	"cm_perm_post": ["Write", "Писать"],
	"cm_perm_manage_hint": ["Edit the community, channels and roles", "Менять сообщество, каналы и роли"],
	"cm_perm_moderate_hint": ["Delete messages, remove and ban members", "Удалять сообщения, убирать и банить"],
	"cm_perm_places_hint": ["Make, edit and publish the community's places in Studio", "Создавать, редактировать и публиковать плейсы сообщества"],
	"cm_perm_post_hint": ["Write in channels", "Писать в каналы"],
	"an_copy": ["Copy id", "Копировать id"],
	"place_updated": ["This place just got updated! Moving you to a fresh server...", "Плейс обновился! Переносим тебя на свежий сервер..."],
	"an_id_none": ["ID: save to get one", "ID: появится после сохранения"],
	"an_id_hint": ["Save the animation: it gets an id like anim://12 for scripts and the emote wheel.", "Сохрани анимацию: она получит id вида anim://12 для скриптов и колеса эмоций."],
	"an_new": ["New", "Новая"],
	"an_open": ["Open", "Открыть"],
	"an_save": ["Save", "Сохранить"],
	"an_close": ["Close", "Закрыть"],
	"an_bone": ["Body part", "Часть тела"],
	"an_rotation": ["Turn, degrees", "Поворот, градусы"],
	"an_move": ["Move, studs", "Сдвиг, стады"],
	"an_tool_rotate": ["Turn (R)", "Вращать (R)"],
	"an_tool_move": ["Move (W)", "Двигать (W)"],
	"an_view_hint": ["Click a body part, drag the gizmo. Right mouse turns the view, wheel zooms, Space plays.", "Кликни по части тела и тяни гизмо. ПКМ крутит вид, колесо зумит, пробел играет."],
	"an_key": ["Set key", "Поставить ключ"],
	"an_delete_key": ["Delete key", "Удалить ключ"],
	"an_hint": ["Move the playhead, click a body part and drag the gizmo: a key is set right there. Melly moves smoothly between keys. Save gives the animation an id for scripts: humanoid:PlayAnimation(\"anim://12\").", "Двигай ползунок времени, кликай по части тела и тяни гизмо: ключ ставится сам. Между ключами Мелли двигается плавно. Сохранение даёт анимации id для скриптов: humanoid:PlayAnimation(\"anim://12\")."],
	"an_saved": ["Saved as {0} (copied)", "Сохранено как {0} (скопировано)"],
	"an_b_Torso": ["Body", "Тело"],
	"an_b_Head": ["Head", "Голова"],
	"an_b_ArmL": ["Left arm", "Левая рука"],
	"an_b_ArmR": ["Right arm", "Правая рука"],
	"an_b_LegL": ["Left leg", "Левая нога"],
	"an_b_LegR": ["Right leg", "Правая нога"],
	"anim_builtin": ["Melly's moves", "Движения Мелли"],
	"anim_mine": ["Made in the Animator (tap an id to copy it)", "Сделанные в аниматоре (тапни по id, чтобы скопировать)"],
	"anim_open_animator": ["Open the Animator", "Открыть аниматор"],
	"anim_none_yet": ["Nothing yet: make one in the Animator.", "Пока ничего: сделай в аниматоре."],
	"anim_idle": ["Stand", "Стоять"],
	"anim_walk": ["Walk", "Идти"],
	"anim_run": ["Run", "Бежать"],
	"anim_wave": ["Wave", "Махать"],
	"anim_dance": ["Dance", "Танцевать"],
	"anim_cheer": ["Cheer", "Радоваться"],
	"anim_sit": ["Sit", "Сидеть"],
	"anim_clap": ["Clap", "Хлопать"],
	"anim_laugh": ["Laugh", "Смеяться"],
	"anim_punch": ["Punch", "Удар"],
	"anim_throw": ["Throw", "Бросок"],
	"shift_lock": ["Shift lock (Ctrl)", "Шифт-лок (Ctrl)"],
	"help_arrows": ["Arrow keys — turn and tilt the camera", "Стрелки — повернуть и наклонить камеру"],
	"help_sprint": ["Shift — run (while you have stamina)", "Shift — бег (пока есть выносливость)"],
	"help_shiftlock": ["Ctrl — shift lock: camera over the shoulder, you face where you look (turn it on in Settings)", "Ctrl — шифт-лок: камера из-за плеча, персонаж смотрит туда же (включается в Настройках)"],
	"st_sounds": ["Sounds", "Звуки"],
	"st_my_sound": ["My sound", "Мой звук"],
	"st_no_sounds": ["No sounds yet. Upload OGG, MP3 or WAV (up to 5 MB each) and use them in Sound objects.", "Звуков пока нет. Загрузи OGG, MP3 или WAV (до 5 МБ каждый) и ставь их в объекты Sound."],
	"st_bad_sound": ["That file isn't an OGG, MP3 or WAV sound", "Это не звук OGG, MP3 или WAV"],
	"st_delete_sound_q": ["Delete this sound?", "Удалить звук?"],
	"bg_title": ["Badges", "Значки"],
	"bg_hint": ["Up to 15 badges. Give them out from a server Script: BadgeService:AwardBadge(player.UserId, id).", "До 15 значков. Выдаются из серверного скрипта: BadgeService:AwardBadge(player.UserId, id)."],
	"bg_row": ["#{0} · {1} have it", "#{0} · есть у {1}"],
	"bg_name": ["Badge name", "Название значка"],
	"bg_desc": ["What for", "За что"],
	"bg_new": ["Add badge", "Добавить значок"],
	"bg_full": ["15 of 15 badges: delete one to add another.", "15 из 15 значков: удали один, чтобы добавить новый."],
	"bg_delete_q": ["Delete badge?", "Удалить значок?"],
	"bg_delete_text": ["Players who have it lose it from their profiles.", "У игроков он пропадёт из профиля."],
	"bg_count": ["Badges: {0}", "Значки: {0}"],
	"bg_all": ["All", "Все"],
	"bg_of": ["{0}'s badges", "Значки {0}"],
	"bg_got": ["New badge: {0}", "Новый значок: {0}"],
	"se_copy_all": ["Copy all", "Копировать всё"],
	"se_copied": ["Script copied", "Скрипт скопирован"],
	"st_insert": ["Insert", "Вставить"],
	"st_rename": ["Rename", "Переименовать"],
	"st_edit_script": ["Edit script", "Открыть скрипт"],
	"st_duplicate": ["Duplicate", "Дублировать"],
	"st_copy": ["Copy", "Копировать"],
	"st_paste_into": ["Paste into", "Вставить внутрь"],
	"st_paste": ["Paste", "Вставить"],
	"st_group": ["Group", "Сгруппировать"],
	"st_ungroup": ["Ungroup", "Разгруппировать"],
	"st_delete": ["Delete", "Удалить"],
	"st_properties": ["Properties", "Свойства"],
	"st_nothing_selected": ["Select something to see its properties", "Выдели что-нибудь, чтобы увидеть свойства"],
	"st_images": ["Images", "Картинки"],
	"st_upload": ["Upload", "Загрузить"],
	"st_asset_usage": ["{0} of {1} files, {2} of {3} MB", "{0} из {1} файлов, {2} из {3} МБ"],
	"st_no_images": ["No images yet. Upload a PNG or JPG to use it as a texture, decal or UI image", "Картинок пока нет. Загрузи PNG или JPG и используй как текстуру, декаль или картинку в UI"],
	"st_use": ["Use", "Выбрать"],
	"st_copy_ref": ["Copy ID", "Копировать ID"],
	"st_copied": ["Copied", "Скопировано"],
	"st_delete_image_q": ["Delete this image?", "Удалить картинку?"],
	"st_uploaded": ["Uploaded", "Загружено"],
	"st_strings": ["Translations", "Переводы"],
	"st_strings_hint": ["Text keys for your place. Write $key in any text, or Strings.get(\"key\") in scripts. Every player sees their own language", "Ключи текста для плейса. Пиши $key в любом тексте или Strings.get(\"key\") в скриптах. Каждый игрок видит свой язык"],
	"st_new_key": ["new_key", "new_key"],
	"st_add_key": ["Add key", "Добавить ключ"],
	"st_add_language": ["Add language", "Добавить язык"],
	"st_key": ["Key", "Ключ"],
	"st_settings": ["Place settings", "Настройки плейса"],
	"st_basics": ["Basics", "Основное"],
	"st_place_name": ["Name", "Название"],
	"st_place_description": ["Description", "Описание"],
	"st_translations": ["Translations", "Переводы"],
	"st_access": ["Who can play", "Кто может играть"],
	"st_vis_private": ["Only me", "Только я"],
	"st_vis_friends": ["Friends", "Друзья"],
	"st_vis_public": ["Everyone", "Все"],
	"st_max_players": ["Max players per server: {0}", "Максимум игроков на сервере: {0}"],
	"st_comments": ["Comments", "Комментарии"],
	"st_covers": ["Covers", "Обложки"],
	"st_cover_wide": ["Wide 16:9", "Широкая 16:9"],
	"st_cover_square": ["Square 1:1", "Квадратная 1:1"],
	"st_take_from_view": ["Take from view", "Снять с камеры"],
	"st_stats": ["Stats", "Статистика"],
	"st_save_publish": ["Save", "Сохранить"],
	"st_visits": ["Visits", "Визиты"],
	"st_players": ["Players", "Игроки"],
	"st_returning": ["Came back", "Вернулись"],
	"st_playtime": ["Total playtime", "Всего наиграно"],
	"st_session": ["Average session", "Средняя сессия"],
	"st_now": ["Playing now", "Играют сейчас"],
	"st_comments_n": ["Comments", "Комментарии"],
	"st_last_30": ["Last 30 days", "Последние 30 дней"],
	"st_place_tab": ["Place", "Плейс"],
	"st_output": ["Output", "Вывод"],
	"st_clear": ["Clear", "Очистить"],
	"st_hint_camera": ["RMB + WASD to fly, wheel to zoom, F to focus", "ПКМ + WASD чтобы летать, колесо для зума, F чтобы навестись"],
	"st_file": ["File", "Файл"],
	"st_save": ["Save", "Сохранить"],
	"st_export": ["Export .melt", "Экспорт .melt"],
	"st_import": ["Import .melt", "Импорт .melt"],
	"st_close": ["Close studio", "Закрыть студию"],
	"st_edit": ["Edit", "Правка"],
	"st_undo": ["Undo", "Отменить"],
	"st_redo": ["Redo", "Повторить"],
	"st_place": ["Place", "Плейс"],
	"st_tool_select": ["Select", "Выбор"],
	"st_tool_move": ["Move", "Двигать"],
	"st_tool_scale": ["Scale", "Размер"],
	"st_tool_rotate": ["Rotate", "Вращать"],
	"st_snap_off": ["No snap", "Без привязки"],
	"st_snap": ["Snap {0}", "Шаг {0}"],
	"st_ui_mode": ["UI", "UI"],
	"st_test": ["Test", "Тест"],
	"st_publish": ["Publish", "Опубликовать"],
	"st_pub_title": ["Publish where?", "Куда опубликовать?"],
	"st_pub_this": ["This place", "Этот плейс"],
	"st_pub_this_hint": ["Save and open its settings: who can play, covers, stats", "Сохранить и открыть его настройки: кто играет, обложки, статистика"],
	"st_pub_new": ["New place page", "Новая страница плейса"],
	"st_pub_new_hint": ["A separate place with its own likes, comments and stats", "Отдельный плейс со своими лайками, комментариями и статистикой"],
	"st_pub_other": ["Replace one of your places", "Заменить один из твоих плейсов"],
	"st_pub_replace_q": ["Replace \"%s\"?", "Заменить «%s»?"],
	"st_pub_replace_text": ["That place gets what's open now. Its name, description, covers, likes and stats stay.", "В тот плейс попадёт то, что открыто сейчас. Название, описание, обложки, лайки и статистика останутся."],
	"st_pub_replace": ["Replace", "Заменить"],
	"st_mobile_title": ["Studio is made for PC", "Студия сделана для ПК"],
	"st_mobile_text": ["It works on phones too, but a mouse and keyboard make it way easier.", "На телефоне тоже работает, но с мышкой и клавой в разы удобнее."],
	"st_continue": ["Continue", "Продолжить"],
	"st_saved_at": ["Saved at {0}", "Сохранено в {0}"],
	"st_unsaved_q": ["Save changes?", "Сохранить изменения?"],
	"st_unsaved_text": ["You have unsaved changes in this place.", "В плейсе есть несохранённые изменения."],
	"st_exported": ["Exported to {0}", "Экспортировано в {0}"],
	"st_bad_file": ["That's not a valid .melt place", "Это не похоже на .melt плейс"],
	"st_need_gui": ["Select a UI element first", "Сначала выдели UI элемент"],
	"st_need_part": ["Select a part first", "Сначала выдели деталь"],
	"st_new_place": ["New place", "Новый плейс"],
	"st_no_places": ["No places yet. Make your first one!", "Плейсов пока нет. Сделай первый!"],
	"st_place_line": ["{0} visits · {1} playing · edited {2}", "{0} визитов · {1} играют · изменён {2}"],
	"st_open": ["Open", "Открыть"],
	"st_create": ["Create", "Создать"],
	"st_delete_place_q": ["Delete this place?", "Удалить плейс?"],

	# Place comments and reports
	"comments": ["Comments", "Комментарии"],
	"comments_off": ["The author turned comments off.", "Автор выключил комментарии."],
	"comment_placeholder": ["Say something nice about this place", "Скажи что-нибудь хорошее про плейс"],
	"comments_too_young": ["Comments open up at 13.", "Комментарии доступны с 13 лет."],
	"no_comments": ["No comments yet. Be the first!", "Комментариев пока нет. Будь первым!"],
	"load_more": ["Show more", "Показать ещё"],
	"delete": ["Delete", "Удалить"],
	"delete_comment_q": ["Delete this comment?", "Удалить комментарий?"],
	"send": ["Send", "Отправить"],
	"report_place_title": ["Report this place", "Пожаловаться на плейс"],
	"report_comment_title": ["Report this comment", "Пожаловаться на комментарий"],
	"report_place": ["Inappropriate place", "Неприемлемый плейс"],
	"report_comment": ["Rude or spam", "Грубость или спам"],
	"recently_played": ["Recently played", "Недавно играли"],
	"joining_from_site": ["Joining from the website...", "Заходим с сайта..."],
	"accessories": ["Accessories", "Аксессуары"],
	"acc_hint": ["Tap to put on or take off. Up to {0} at once, one per spot.", "Нажми, чтобы надеть или снять. До {0} штук, по одной на каждое место."],
	"acc_take_off": ["Take all off", "Снять всё"],
}
