class_name Strings
extends RefCounted
## UI text: key -> [English, Russian]. Plural keys hold forms joined by "|":
## English "one|many", Russian "one|few|many".

const TABLE := {
	# General
	"yes": ["Yes", "Да"],
	"cancel": ["Cancel", "Отмена"],
	"close": ["Close", "Закрыть"],
	"load_failed": ["Couldn't load. Check your internet", "Не получилось загрузить. Проверь интернет"],
	"loading_places": ["Loading places...", "Загружаем плейсы..."],
	"retry": ["Try again", "Попробовать снова"],
	"connecting": ["Connecting...", "Подключаемся..."],
	"one_sec": ["One sec...", "Секунду..."],
	"done": ["Done", "Готово"],
	"apply": ["Apply", "Применить"],
	"save": ["Save", "Сохранить"],
	"saved": ["Saved", "Сохранено"],
	"saving": ["Saving...", "Сохраняем..."],
	"time_now": ["just now", "только что"],
	"time_min": ["{0} min ago", "{0} мин назад"],
	"time_hour": ["{0} h ago", "{0} ч назад"],
	"time_day": ["{0} d ago", "{0} дн назад"],
	"session_expired": ["Session expired, please sign in again", "Сессия истекла, войди заново"],
	"err_request": ["Couldn't send the request", "Не получилось отправить запрос"],
	"err_network": ["No connection to the server. Check your internet", "Нет связи с сервером. Проверь интернет"],
	"err_server": ["Server error ({0})", "Ошибка сервера ({0})"],
	"err_ws_connect": ["Couldn't connect to the game server", "Не удалось подключиться к игровому серверу"],
	"err_ws_lost": ["Connection to the server was lost", "Соединение с сервером потеряно"],
	"err_ws_unavailable": ["Game server is unavailable", "Игровой сервер недоступен"],
	"err_duplicate": ["You joined from another device", "Ты зашёл(ла) в игру с другого устройства"],

	# Auth
	"tagline": ["Play, dress up and hang out with friends", "Играй, наряжайся и тусуйся с друзьями"],
	"sign_in": ["Sign in", "Вход"],
	"sign_up": ["Sign up", "Регистрация"],
	"username": ["Username", "Логин"],
	"display_name_hint": ["Display name (what others see)", "Как тебя называть (ник)"],
	"password": ["Password", "Пароль"],
	"password_repeat": ["Repeat password", "Повтори пароль"],
	"create_account": ["Create account", "Создать аккаунт"],
	"register_hint": ["Username: latin letters, digits and _. Password: 6+ characters.", "Логин: латиница, цифры и _. Пароль от 6 символов."],
	"login_hint": ["No account yet? Tap Sign up, it takes a minute.", "Нет аккаунта? Жми «Регистрация», это быстро."],
	"bad_username": ["Username: 3–20 characters, latin letters, digits and _", "Логин: 3–20 символов, латиница, цифры и _"],
	"bad_password": ["Password must be at least 6 characters", "Пароль должен быть от 6 символов"],
	"passwords_mismatch": ["Passwords don't match", "Пароли не совпадают"],
	"welcome_name": ["Welcome, {0}!", "Добро пожаловать, {0}!"],

	# Navigation
	"nav_home": ["Home", "Главная"],
	"nav_friends": ["Friends", "Друзья"],
	"nav_avatar": ["Avatar", "Аватар"],
	"nav_settings": ["Settings", "Настройки"],

	# Home
	"hello_name": ["Hi, {0}!", "Привет, {0}!"],
	"home_sub": ["What are we playing today?", "Во что сегодня играем?"],
	"friends_online": ["Friends online", "Друзья онлайн"],
	"servers_title": ["Servers", "Серверы"],
	"new_server": ["New server", "Новый сервер"],
	"loading_servers": ["Loading servers...", "Загружаем серверы..."],
	"featured_tag": ["FEATURED", "ИЗБРАННОЕ"],
	"playground": ["Playground", "Детская площадка"],
	"playground_desc": ["Slides, swings, trampolines, a hedge maze, a pond and parkour above the clouds. Up to 10 players per server.", "Горки, качели, батуты, лабиринт, пруд и паркур над облаками. До 10 игроков на сервер."],
	"play": ["Play", "Играть"],
	"playing_now": ["{0} {1} on the playground now", "{0} {1} сейчас на площадке"],
	"players_word": ["player|players", "игрок|игрока|игроков"],
	"friends_word": ["friend|friends", "друг|друга|друзей"],
	"no_servers": ["No servers yet. Tap Play and the first one is yours.", "Пока ни одного сервера. Жми «Играть», и первый будет твоим."],
	"friends_here": ["Friends here: {0}", "Здесь друзья: {0}"],
	"server_id": ["Server #{0}", "Сервер #{0}"],
	"full": ["Full", "Полный"],
	"join": ["Join", "Войти"],
	"on_playground": ["On the playground", "На площадке"],
	"in_menu": ["In menu", "В меню"],

	# Friends
	"friends_sub": ["Find friends by name and play on the same server", "Найди друзей по нику и играйте на одном сервере"],
	"search_players": ["Search players by name or username", "Поиск игроков по нику или логину"],
	"my_friends": ["My friends", "Мои друзья"],
	"requests": ["Requests", "Заявки"],
	"sent": ["Sent", "Отправленные"],
	"no_friends": ["No friends yet. Find someone with the search above!", "Пока друзей нет. Найди кого-нибудь через поиск сверху!"],
	"no_requests": ["No new requests", "Новых заявок нет"],
	"no_sent": ["You haven't sent any requests", "Ты никому не отправлял(а) заявок"],
	"nobody_found": ["Nobody found for “{0}”", "Никого не нашли по запросу «{0}»"],
	"playing_on": ["Playing: {0}", "Играет: {0}"],
	"online": ["Online", "В сети"],
	"offline": ["Offline", "Не в сети"],
	"join_friend": ["Join", "Присоединиться"],
	"remove": ["Remove", "Удалить"],
	"accept": ["Accept", "Принять"],
	"decline": ["Decline", "Отклонить"],
	"cancel_request": ["Cancel request", "Отменить"],
	"add": ["Add", "Добавить"],
	"add_friend": ["Add friend", "Добавить в друзья"],
	"remove_friend": ["Remove friend", "Удалить из друзей"],
	"accept_request": ["Accept request", "Принять заявку"],
	"now_friends_with": ["You and {0} are friends now", "Теперь вы друзья с {0}"],
	"now_friends": ["You're friends now!", "Вы теперь друзья!"],
	"request_sent": ["Friend request sent", "Заявка отправлена"],
	"request_sent_short": ["Sent", "Отправлено"],
	"friends_badge": ["Friends", "Друзья"],
	"request_cancelled": ["Request cancelled", "Заявка отменена"],
	"remove_friend_q": ["Remove friend?", "Удалить из друзей?"],
	"remove_friend_body": ["{0} will disappear from your friends list.", "{0} пропадёт из списка друзей."],
	"removed": ["Removed", "Удалено"],
	"mutual_request": ["They had already asked you, so you're friends now!", "У вас была встречная заявка, теперь вы друзья!"],
	"block": ["Block", "Заблокировать"],
	"unblock": ["Unblock", "Разблокировать"],
	"block_q": ["Block {0}?", "Заблокировать {0}?"],
	"block_body": ["You won't see their chat messages and they can't send you friend requests.", "Ты не увидишь их сообщения в чате, и они не смогут кинуть тебе заявку в друзья."],
	"blocked_done": ["Player blocked", "Игрок заблокирован"],
	"unblocked": ["Player unblocked", "Игрок разблокирован"],

	# Profile
	"loading_profile": ["Loading profile...", "Загружаем профиль..."],
	"no_bio": ["Hasn't written anything about themselves yet", "Пока ничего о себе не рассказал(а)"],
	"member_since": ["member since", "с нами с"],

	# Avatar
	"wave": ["Wave", "Помахать"],
	"random": ["Random", "Случайно"],
	"like_melly": ["Classic Melly", "Как у Melly"],
	"colors": ["Colors", "Цвета"],
	"hats": ["Hats", "Шапки"],
	"profile": ["Profile", "Профиль"],
	"what_to_paint": ["What to paint", "Что красим"],
	"whole_body": ["Whole body", "Всё тело"],
	"both_arms": ["Both arms", "Обе руки"],
	"both_legs": ["Both legs", "Обе ноги"],
	"part_head": ["Head", "Голова"],
	"part_torso": ["Torso", "Торс"],
	"part_arm_l": ["Left arm", "Левая рука"],
	"part_arm_r": ["Right arm", "Правая рука"],
	"part_leg_l": ["Left leg", "Левая нога"],
	"part_leg_r": ["Right leg", "Правая нога"],
	"color": ["Color", "Цвет"],
	"custom_color": ["Custom color", "Свой цвет"],
	"hat_none": ["No hat", "Без шапки"],
	"hat_catears": ["Cat ears", "Кошачьи ушки"],
	"hat_cap": ["Cap", "Кепка"],
	"hat_crown": ["Crown", "Корона"],
	"hat_halo": ["Halo", "Нимб"],
	"hat_tophat": ["Top hat", "Цилиндр"],
	"hat_flower": ["Flower", "Цветочек"],
	"hat_headphones": ["Headphones", "Наушники"],
	"nick_label": ["Display name (everyone on the server sees it)", "Ник (видят все на сервере)"],
	"nick": ["Display name", "Ник"],
	"about_me": ["About me", "О себе"],
	"bio_hint": ["A few words about you (up to 160 characters)", "Пара слов о себе (до 160 символов)"],
	"login_is": ["Username: @{0}", "Логин: @{0}"],
	"nick_short": ["Display name is too short", "Ник слишком короткий"],
	"look_saved": ["Look saved", "Образ сохранён"],

	# Settings
	"game": ["Game", "Игра"],
	"camera_sensitivity": ["Camera sensitivity", "Чувствительность камеры"],
	"volume": ["Volume", "Громкость"],
	"graphics": ["Graphics", "Графика"],
	"quality_low": ["Fast", "Быстрая"],
	"quality_medium": ["Balanced", "Средняя"],
	"quality_high": ["Pretty", "Красивая"],
	"graphics_note": ["Fast turns off shadows and effects; use it on older phones.", "«Быстрая» выключает тени и эффекты, выбирай её на старых телефонах."],
	"show_fps": ["Show FPS and ping", "Показывать FPS и пинг"],
	"language": ["Language", "Язык"],
	"about": ["About", "О приложении"],
	"server_is": ["Server: {0}", "Сервер: {0}"],
	"checking_server": ["Checking connection...", "Проверяем связь..."],
	"server_ok": ["Server is fine, {0} ms, accounts: {1}", "Сервер в порядке, отклик {0} мс, аккаунтов: {1}"],
	"server_down": ["Server unavailable: {0}", "Сервер недоступен: {0}"],
	"account": ["Account", "Аккаунт"],
	"signed_in_as": ["Signed in as @{0}", "Вошли как @{0}"],
	"change_password": ["Change password", "Сменить пароль"],
	"current_password": ["Current password", "Текущий пароль"],
	"new_password": ["New password (6+ characters)", "Новый пароль (от 6 символов)"],
	"password_changed": ["Password changed. Other devices were signed out", "Пароль изменён. Другие устройства разлогинены"],
	"log_out": ["Sign out", "Выйти из аккаунта"],
	"log_out_q": ["Sign out?", "Выйти?"],
	"log_out_body": ["You'll need your username and password to come back.", "Чтобы вернуться, понадобятся логин и пароль."],
	"blocked_players": ["Blocked players", "Заблокированные"],
	"nobody_blocked": ["You haven't blocked anyone", "Ты никого не блокировал(а)"],

	# Game
	"joining_playground": ["Joining the playground...", "Подключаемся к площадке..."],
	"reconnecting": ["Reconnecting ({0}/3)...", "Переподключаемся ({0}/3)..."],
	"to_menu": ["Main menu", "В меню"],
	"other_server": ["Another server", "Другой сервер"],
	"finding_server": ["Looking for a free server...", "Ищем свободный сервер..."],
	"welcome_server": ["You're on “{0}”. Have fun!", "Ты на сервере «{0}». Веселись!"],
	"sys_joined": ["{0} joined the playground", "{0} зашёл(ла) на площадку"],
	"sys_left": ["{0} left", "{0} ушёл(ла)"],
	"sys_slow": ["Slow down, the chat can't keep up :)", "Помедленнее, чат не успевает :)"],
	"chat_placeholder": ["Say something...", "Написать в чат..."],
	"stats": ["{0} FPS · ping {1}", "{0} FPS · пинг {1}"],
	"you_fell_apart": ["Oof! Respawning...", "Ой! Собираемся обратно..."],
	"island_reached": ["You made it to the clouds!", "Ты добрался(ась) до облаков!"],
	"maze_solved": ["Maze solved! You found the golden flower", "Лабиринт пройден! Золотой цветок твой"],
	"leave_q": ["Leave the playground?", "Выйти с площадки?"],
	"leave_body": ["You'll go back to the main menu.", "Вернёшься в главное меню."],
	"leave_game": ["Leave game", "Выйти из игры"],
	"reset_character": ["Reset character", "Ресетнуться"],
	"resume": ["Resume", "Продолжить"],
	"players": ["Players", "Игроки"],
	"controls": ["Controls", "Управление"],
	"players_on_server": ["Players on server ({0}/{1})", "Игроки на сервере ({0}/{1})"],
	"its_you": ["that's you", "это ты"],
	"help_move": ["Move: left thumb (joystick) or WASD. Shift to sprint on PC.", "Ходить: левый палец (джойстик) или WASD. Shift на ПК для бега."],
	"help_camera": ["Camera: drag with the right thumb, or hold the right mouse button.", "Камера: веди правым пальцем или держи правую кнопку мыши."],
	"help_zoom": ["Zoom: pinch or mouse wheel. Zoom all the way in (or the camera button) for first person.", "Зум: щипок или колесо мыши. Приблизь до упора (или кнопка камеры) для вида от первого лица."],
	"help_jump": ["Jump: big button on the right or Space. Big falls hurt!", "Прыжок: большая кнопка справа или пробел. Падать с высоты больно!"],
	"help_emotes": ["Emotes: the smiley button or B opens the emote wheel.", "Эмоции: кнопка со смайликом или B открывает колесо эмоций."],
	"help_chat": ["Chat: the chat button or Enter.", "Чат: кнопка чата или Enter."],
	"help_reset": ["Stuck? Menu → Reset character (or R).", "Застрял(а)? Меню → Ресетнуться (или R)."],
	"emote_wave": ["Wave", "Привет"],
	"emote_heart": ["Hearts", "Сердечки"],
	"emote_dance": ["Dance", "Танец"],
	"emote_cheer": ["Cheer", "Ура!"],
	"emote_sit": ["Sit", "Сесть"],
	"emote_clap": ["Clap", "Хлопать"],
	"emote_laugh": ["Laugh", "Смех"],

	"places": ["Places", "Плейсы"],
	"by": ["by", "от"],
	"n_playing": ["{0} playing", "играют: {0}"],
	"n_visits": ["{0} visits", "посещений: {0}"],
	"rating": ["{0} liked", "{0} лайков"],
	"back": ["Back", "Назад"],
	"loading": ["Loading...", "Загрузка..."],
	"about_place": ["About", "Описание"],
	"created_on": ["Created {0}", "Создан {0}"],
	"play_hint": ["Play puts you on a server with your friends if any are playing.", "«Играть» закинет тебя на сервер к друзьям, если они играют."],
	"update_title": ["Time to update", "Пора обновиться"],
	"update_body": ["A new version of Meltiew is out. Download it to keep playing.", "Вышла новая версия Meltiew. Скачай её, чтобы играть дальше."],
	"update_button": ["Download update", "Скачать обновление"],
	"your_version": ["Your version: {0}", "Твоя версия: {0}"],
	"kicked_banned": ["Your account was banned", "Твой аккаунт заблокирован"],
	"kicked_admin": ["An admin removed you from the server", "Админ выгнал тебя с сервера"],
	"server_closed": ["This server was closed", "Этот сервер закрыли"],
	"role_owner": ["OWNER", "ОВНЕР"],
	"role_admin": ["ADMIN", "АДМИН"],

	# Round 4
	"messages": ["Messages", "Сообщения"],
	"chats": ["Chats", "Чаты"],
	"dm_requests": ["Requests", "Заявки"],
	"no_chats": ["No conversations yet. Open a profile and press Message.", "Пока нет диалогов. Открой профиль и нажми «Написать»."],
	"no_requests_dm": ["No message requests", "Заявок на диалог нет"],
	"pick_chat": ["Pick a conversation", "Выбери диалог"],
	"you_prefix": ["You: ", "Ты: "],
	"type_message": ["Message...", "Сообщение..."],
	"message": ["Message", "Написать"],
	"dm_waiting": ["Message request sent. You can write more once {0} accepts it.", "Заявка отправлена. Написать ещё можно будет, когда {0} её примет."],
	"dm_request_from": ["{0} wants to chat with you", "{0} хочет с тобой пообщаться"],
	"dm_first_message": ["You're not friends yet: your first message goes as a request.", "Вы ещё не друзья: первое сообщение уйдёт как заявка на диалог."],
	"dm_unavailable_note": ["Messages aren't available for this conversation.", "В этом диалоге сообщения недоступны."],
	"friends_online_n": ["{0} online of {1}", "{0} в сети из {1}"],
	"search_everything": ["Search players and places", "Поиск игроков и плейсов"],
	"search_places": ["Search places", "Поиск плейсов"],
	"no_places_found": ["No places found", "Ничего не нашлось"],
	"friends_hidden": ["Friends list is hidden", "Список друзей скрыт"],
	"report": ["Report", "Пожаловаться"],
	"report_title": ["Report {0}", "Жалоба на {0}"],
	"report_chat": ["Chat", "Чат"],
	"report_name": ["Name", "Ник"],
	"report_avatar": ["Avatar", "Аватар"],
	"report_cheating": ["Cheating", "Читы"],
	"report_other": ["Other", "Другое"],
	"report_details": ["What happened? (optional)", "Что случилось? (необязательно)"],
	"report_send": ["Send report", "Отправить"],
	"faces": ["Face", "Лицо"],
	"interface": ["Interface", "Интерфейс"],
	"ui_size": ["Interface size", "Размер интерфейса"],
	"ui_size_auto": ["Automatic size", "Размер автоматически"],
	"lang_fallback_note": ["The app isn't translated to this language yet, so it shows English. Places that have their own translations will use it.", "Приложение пока не переведено на этот язык, поэтому показывает английский. Плейсы со своими переводами будут на нём."],
	"console": ["Console", "Консоль"],
	"place_unsupported": ["Scripts can't run on this device, so the place may not work.", "На этом устройстве скрипты не запускаются, поэтому плейс может не работать."],
	"loading_place": ["Loading the place...", "Загружаем плейс..."],
	"telegram": ["Our Telegram channel", "Наш Telegram-канал"],
	"privacy": ["Privacy", "Приватность"],
	"hide_friends": ["Hide my friends list", "Скрыть список друзей"],
	"bd_title": ["Your date of birth", "Твоя дата рождения"],
	"bd_why": ["We need it to set up chat safely. Enter the real one: after one free fix it can only be changed once every 6 months.", "Она нужна, чтобы безопасно настроить чат. Укажи настоящую: после одного бесплатного исправления менять её можно раз в полгода."],
	"bd_change_why": ["Pick your real date of birth. After this change the next one is possible in 6 months.", "Выбери настоящую дату рождения. После этой смены следующая будет доступна через полгода."],
	"bd_change_free": ["Fix date of birth (one free change)", "Исправить дату рождения (одна бесплатная смена)"],
	"bd_change": ["Change date of birth", "Сменить дату рождения"],
	"bd_next_change": ["You can change it again on {0}.", "Снова сменить можно будет {0}."],
	"bd_label": ["Date of birth", "Дата рождения"],
	"bd_day": ["Day", "День"],
	"bd_month": ["Month", "Месяц"],
	"bd_year": ["Year", "Год"],
	"bd_months": ["January,February,March,April,May,June,July,August,September,October,November,December", "января,февраля,марта,апреля,мая,июня,июля,августа,сентября,октября,ноября,декабря"],
	"bd_later": ["Later", "Позже"],
	"bd_incomplete": ["Pick day, month and year", "Выбери день, месяц и год"],
	"bd_is": ["Date of birth: {0}", "Дата рождения: {0}"],
	"birthdate_needed": ["Enter your date of birth to play", "Укажи дату рождения, чтобы играть"],
	"rules_kid": ["Under 13: chat and direct messages are off.", "До 13 лет: чат и личные сообщения выключены."],
	"rules_teen": ["Under 16: chat and direct messages are filtered.", "До 16 лет: в чате и личных сообщениях работает фильтр."],
	"rules_older_teen": ["Under 18: game chat is filtered.", "До 18 лет: в игровом чате работает фильтр."],
	"rules_adult": ["18+: no filters.", "18+: без фильтров."],
	"sys_no_chat": ["Chat is off for your age", "Чат недоступен по возрасту"],

	# World signs
	"sign_trampolines": ["trampolines", "батуты"],
	"sign_maze": ["hedge maze", "лабиринт"],
	"sign_parkour": ["parkour to the clouds", "паркур до облаков"],
	"sign_pond": ["duck pond", "утиный пруд"],
	"sign_icecream": ["ICE CREAM", "МОРОЖЕНОЕ"],

	# Studio
	"nav_studio": ["Studio", "Студия"],
	"studio_sub": ["Build your own places, script them in Luau and publish", "Строй свои плейсы, пиши скрипты на Luau и публикуй"],
	"bad_image": ["That image didn't work. Try a PNG or JPG up to 2 MB", "Картинка не подошла. Нужен PNG или JPG до 2 МБ"],
	"st_explorer": ["Explorer", "Проводник"],
	"st_insert": ["Insert", "Вставить"],
	"st_rename": ["Rename", "Переименовать"],
	"st_edit_script": ["Edit script", "Открыть скрипт"],
	"st_duplicate": ["Duplicate", "Дублировать"],
	"st_copy": ["Copy", "Копировать"],
	"st_paste_into": ["Paste into", "Вставить внутрь"],
	"st_paste": ["Paste", "Вставить"],
	"st_group": ["Group", "Сгруппировать"],
	"st_ungroup": ["Ungroup", "Разгруппировать"],
	"st_delete": ["Delete", "Удалить"],
	"st_properties": ["Properties", "Свойства"],
	"st_nothing_selected": ["Select something to see its properties", "Выдели что-нибудь, чтобы увидеть свойства"],
	"st_images": ["Images", "Картинки"],
	"st_upload": ["Upload", "Загрузить"],
	"st_asset_usage": ["{0} of {1} images, {2} of {3} MB", "{0} из {1} картинок, {2} из {3} МБ"],
	"st_no_images": ["No images yet. Upload a PNG or JPG to use it as a texture, decal or UI image", "Картинок пока нет. Загрузи PNG или JPG и используй как текстуру, декаль или картинку в UI"],
	"st_use": ["Use", "Выбрать"],
	"st_copy_ref": ["Copy ID", "Копировать ID"],
	"st_copied": ["Copied", "Скопировано"],
	"st_delete_image_q": ["Delete this image?", "Удалить картинку?"],
	"st_uploaded": ["Uploaded", "Загружено"],
	"st_strings": ["Translations", "Переводы"],
	"st_strings_hint": ["Text keys for your place. Write $key in any text, or Strings.get(\"key\") in scripts. Every player sees their own language", "Ключи текста для плейса. Пиши $key в любом тексте или Strings.get(\"key\") в скриптах. Каждый игрок видит свой язык"],
	"st_new_key": ["new_key", "new_key"],
	"st_add_key": ["Add key", "Добавить ключ"],
	"st_add_language": ["Add language", "Добавить язык"],
	"st_key": ["Key", "Ключ"],
	"st_settings": ["Place settings", "Настройки плейса"],
	"st_basics": ["Basics", "Основное"],
	"st_place_name": ["Name", "Название"],
	"st_place_description": ["Description", "Описание"],
	"st_translations": ["Translations", "Переводы"],
	"st_access": ["Who can play", "Кто может играть"],
	"st_vis_private": ["Only me", "Только я"],
	"st_vis_friends": ["Friends", "Друзья"],
	"st_vis_public": ["Everyone", "Все"],
	"st_max_players": ["Max players per server", "Максимум игроков на сервере"],
	"st_comments": ["Comments", "Комментарии"],
	"st_covers": ["Covers", "Обложки"],
	"st_cover_wide": ["Wide 16:9", "Широкая 16:9"],
	"st_cover_square": ["Square 1:1", "Квадратная 1:1"],
	"st_take_from_view": ["Take from view", "Снять с камеры"],
	"st_stats": ["Stats", "Статистика"],
	"st_save_publish": ["Save", "Сохранить"],
	"st_visits": ["Visits", "Визиты"],
	"st_players": ["Players", "Игроки"],
	"st_returning": ["Came back", "Вернулись"],
	"st_playtime": ["Total playtime", "Всего наиграно"],
	"st_session": ["Average session", "Средняя сессия"],
	"st_now": ["Playing now", "Играют сейчас"],
	"st_comments_n": ["Comments", "Комментарии"],
	"st_last_30": ["Last 30 days", "Последние 30 дней"],
	"st_place_tab": ["Place", "Плейс"],
	"st_output": ["Output", "Вывод"],
	"st_clear": ["Clear", "Очистить"],
	"st_hint_camera": ["RMB + WASD to fly, wheel to zoom, F to focus", "ПКМ + WASD чтобы летать, колесо для зума, F чтобы навестись"],
	"st_file": ["File", "Файл"],
	"st_save": ["Save", "Сохранить"],
	"st_export": ["Export .marp", "Экспорт .marp"],
	"st_import": ["Import .marp", "Импорт .marp"],
	"st_close": ["Close studio", "Закрыть студию"],
	"st_edit": ["Edit", "Правка"],
	"st_undo": ["Undo", "Отменить"],
	"st_redo": ["Redo", "Повторить"],
	"st_place": ["Place", "Плейс"],
	"st_tool_select": ["Select", "Выбор"],
	"st_tool_move": ["Move", "Двигать"],
	"st_tool_scale": ["Scale", "Размер"],
	"st_tool_rotate": ["Rotate", "Вращать"],
	"st_snap_off": ["No snap", "Без привязки"],
	"st_snap": ["Snap {0}", "Шаг {0}"],
	"st_ui_mode": ["UI", "UI"],
	"st_test": ["Test", "Тест"],
	"st_publish": ["Publish", "Опубликовать"],
	"st_mobile_title": ["Studio is made for PC", "Студия сделана для ПК"],
	"st_mobile_text": ["It works on phones too, but a mouse and keyboard make it way easier.", "На телефоне тоже работает, но с мышкой и клавой в разы удобнее."],
	"st_continue": ["Continue", "Продолжить"],
	"st_saved_at": ["Saved at {0}", "Сохранено в {0}"],
	"st_unsaved_q": ["Save changes?", "Сохранить изменения?"],
	"st_unsaved_text": ["You have unsaved changes in this place.", "В плейсе есть несохранённые изменения."],
	"st_exported": ["Exported to {0}", "Экспортировано в {0}"],
	"st_bad_file": ["That's not a valid .marp place", "Это не похоже на .marp плейс"],
	"st_need_gui": ["Select a UI element first", "Сначала выдели UI элемент"],
	"st_need_part": ["Select a part first", "Сначала выдели деталь"],
	"st_new_place": ["New place", "Новый плейс"],
	"st_no_places": ["No places yet. Make your first one!", "Плейсов пока нет. Сделай первый!"],
	"st_place_line": ["{0} visits · {1} playing · edited {2}", "{0} визитов · {1} играют · изменён {2}"],
	"st_open": ["Open", "Открыть"],
	"st_create": ["Create", "Создать"],
	"st_delete_place_q": ["Delete this place?", "Удалить плейс?"],

	# Place comments and reports
	"comments": ["Comments", "Комментарии"],
	"comments_off": ["The author turned comments off.", "Автор выключил комментарии."],
	"comment_placeholder": ["Say something nice about this place", "Скажи что-нибудь хорошее про плейс"],
	"comments_too_young": ["Comments open up at 13.", "Комментарии доступны с 13 лет."],
	"no_comments": ["No comments yet. Be the first!", "Комментариев пока нет. Будь первым!"],
	"load_more": ["Show more", "Показать ещё"],
	"delete": ["Delete", "Удалить"],
	"delete_comment_q": ["Delete this comment?", "Удалить комментарий?"],
	"send": ["Send", "Отправить"],
	"report_place_title": ["Report this place", "Пожаловаться на плейс"],
	"report_comment_title": ["Report this comment", "Пожаловаться на комментарий"],
	"report_place": ["Inappropriate place", "Неприемлемый плейс"],
	"report_comment": ["Rude or spam", "Грубость или спам"],
}
